const productsList = [
  {
    id: 1,
    title: "Dell Inspiron 15 Laptop",
    price: 850.0,
    description: "15.6-inch laptop with Intel Core i7, 16GB RAM, 512GB SSD.",
    category: "Laptops&Computers",
    image: "https://m.media-amazon.com/images/I/71Z2C0m+d7L._AC_SL1500_.jpg",
    offer: "15% OFF",
    offerPrice: 722.5,
    finalPrice: 722.5,
    quantity: 20,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.3,
      count: 256,
    },
  },
  {
    id: 2,
    title: "Apple MacBook Air M2",
    price: 1199.0,
    description:
      "Apple MacBook Air with M2 chip, 13.6-inch Retina Display, 8GB RAM, 256GB SSD.",
    category: "Laptops&Computers",
    image: "https://m.media-amazon.com/images/I/81xW62KXNhL._AC_SL1500_.jpg",
    offer: "10% OFF",
    offerPrice: 1079.1,
    finalPrice: 1079.1,
    quantity: 15,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.8,
      count: 423,
    },
  },
  {
    id: 3,
    title: "HP Pavilion x360",
    price: 699.99,
    description:
      "2-in-1 convertible laptop, Intel i5, 8GB RAM, 256GB SSD, 14-inch touchscreen.",
    category: "Laptops&Computers",
    image: "https://m.media-amazon.com/images/I/81gV5NJZ6+L._AC_SL1500_.jpg",
    offer: "12% OFF",
    offerPrice: 615.99,
    finalPrice: 615.99,
    quantity: 25,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.2,
      count: 187,
    },
  },
  {
    id: 4,
    title: "Lenovo Legion 5 Gaming Laptop",
    price: 1299.0,
    description: "15.6-inch FHD, AMD Ryzen 7, 16GB RAM, RTX 3060, 1TB SSD.",
    category: "Laptops&Computers",
    image: "https://m.media-amazon.com/images/I/91LCDTwJcNL._AC_SL1500_.jpg",
    offer: "18% OFF",
    offerPrice: 1065.18,
    finalPrice: 1065.18,
    quantity: 10,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.6,
      count: 98,
    },
  },
  {
    id: 5,
    title: "Acer Aspire Desktop PC",
    price: 499.0,
    description: "Intel Core i3, 8GB RAM, 1TB HDD, Windows 11 Home.",
    category: "Laptops&Computers",
    image: "https://m.media-amazon.com/images/I/61jHgpFNqgL._AC_SL1500_.jpg",
    offer: "20% OFF",
    offerPrice: 399.2,
    finalPrice: 399.2,
    quantity: 30,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.0,
      count: 145,
    },
  },
  {
    id: 6,
    title: "Dell OptiPlex 7090 Micro Desktop",
    price: 899.0,
    description: "Intel Core i5, 16GB RAM, 512GB SSD, compact business PC.",
    category: "Laptops&Computers",
    image: "https://m.media-amazon.com/images/I/51cQ9dOdLlL._AC_SL1080_.jpg",
    offer: "10% OFF",
    offerPrice: 809.1,
    finalPrice: 809.1,
    quantity: 18,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.4,
      count: 120,
    },
  },
  {
    id: 7,
    title: "Apple Mac Mini M2",
    price: 699.0,
    description: "Apple desktop powered by M2 chip, 8GB RAM, 256GB SSD.",
    category: "Laptops&Computers",
    image: "https://m.media-amazon.com/images/I/41ep3g2AD5L._AC_SL1200_.jpg",
    offer: "7% OFF",
    offerPrice: 650.07,
    finalPrice: 650.07,
    quantity: 12,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.7,
      count: 174,
    },
  },
  {
    id: 8,
    title: "MSI MAG Infinite Gaming Desktop",
    price: 1599.0,
    description: "Intel Core i7, 32GB RAM, RTX 4070, 1TB SSD, RGB case.",
    category: "Laptops&Computers",
    image: "https://m.media-amazon.com/images/I/71vwUaL5zDL._AC_SL1500_.jpg",
    offer: "22% OFF",
    offerPrice: 1247.22,
    finalPrice: 1247.22,
    quantity: 8,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.5,
      count: 65,
    },
  },
  {
    id: 9,
    title: "Apple iPhone 14 Pro Max",
    price: 1199.0,
    description:
      "6.7-inch Super Retina XDR display, A16 Bionic chip, 256GB storage.",
    category: "Smartphones",
    image: "https://m.media-amazon.com/images/I/61itehvdgsL._AC_SL1500_.jpg",
    offer: "10% OFF",
    offerPrice: 1079.1,
    finalPrice: 1079.1,
    quantity: 20,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.9,
      count: 1020,
    },
  },
  {
    id: 10,
    title: "Samsung Galaxy S23 Ultra",
    price: 1299.99,
    description:
      "6.8-inch Dynamic AMOLED 2X, Snapdragon 8 Gen 2, 12GB RAM, 512GB.",
    category: "Smartphones",
    image: "https://m.media-amazon.com/images/I/71Sa3dqTqzL._AC_SL1500_.jpg",
    offer: "15% OFF",
    offerPrice: 1104.99,
    finalPrice: 1104.99,
    quantity: 25,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.8,
      count: 875,
    },
  },
  {
    id: 11,
    title: "Google Pixel 7 Pro",
    price: 899.0,
    description:
      "6.7-inch OLED display, Google Tensor G2, 12GB RAM, 128GB storage.",
    category: "Smartphones",
    image: "https://m.media-amazon.com/images/I/615rI0PoyOL._AC_SL1500_.jpg",
    offer: "12% OFF",
    offerPrice: 791.12,
    finalPrice: 791.12,
    quantity: 18,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.6,
      count: 630,
    },
  },
  {
    id: 12,
    title: "OnePlus 11 5G",
    price: 699.99,
    description: "Snapdragon 8 Gen 2, 6.7-inch AMOLED, 16GB RAM, 256GB.",
    category: "Smartphones",
    image: "https://m.media-amazon.com/images/I/81fRAoUL-fL._AC_SL1500_.jpg",
    offer: "18% OFF",
    offerPrice: 573.99,
    finalPrice: 573.99,
    quantity: 30,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.5,
      count: 450,
    },
  },
  {
    id: 13,
    title: "Xiaomi 13 Pro",
    price: 899.0,
    description: "Snapdragon 8 Gen 2, 120Hz AMOLED, Leica camera, 12GB RAM.",
    category: "Smartphones",
    image: "https://m.media-amazon.com/images/I/51ujrY0Md7L._AC_SL1500_.jpg",
    offer: "20% OFF",
    offerPrice: 719.2,
    finalPrice: 719.2,
    quantity: 22,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.4,
      count: 380,
    },
  },
  {
    id: 14,
    title: "Motorola Edge 40 Pro",
    price: 799.0,
    description: "6.67-inch OLED 165Hz, Snapdragon 8 Gen 2, 12GB RAM.",
    category: "Smartphones",
    image: "https://m.media-amazon.com/images/I/61sTY-hT9KL._AC_SL1500_.jpg",
    offer: "17% OFF",
    offerPrice: 663.17,
    finalPrice: 663.17,
    quantity: 17,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.3,
      count: 280,
    },
  },
  {
    id: 15,
    title: "Sony Xperia 1 V",
    price: 1399.0,
    description: "6.5-inch 4K OLED, Snapdragon 8 Gen 2, triple camera setup.",
    category: "Smartphones",
    image: "https://m.media-amazon.com/images/I/61G9Nz-DbuL._AC_SL1500_.jpg",
    offer: "14% OFF",
    offerPrice: 1203.14,
    finalPrice: 1203.14,
    quantity: 12,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.2,
      count: 190,
    },
  },
  {
    id: 16,
    title: "Asus ROG Phone 7",
    price: 1099.0,
    description:
      "Gaming phone with AMOLED 165Hz display, Snapdragon 8 Gen 2, 16GB RAM.",
    category: "Smartphones",
    image: "https://m.media-amazon.com/images/I/518RsOS8u4L._AC_SL1080_.jpg",
    offer: "0",
    offerPrice: 0,
    finalPrice: 1099.0,
    quantity: 10,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.6,
      count: 220,
    },
  },
  {
    id: 17,
    title: "Realme GT Neo 5",
    price: 599.0,
    description: "Snapdragon 8+ Gen 1, 144Hz AMOLED, 150W fast charging.",
    category: "Smartphones",
    image: "https://m.media-amazon.com/images/I/718p48pvjPL._AC_SL1500_.jpg",
    offer: "22% OFF",
    offerPrice: 467.22,
    finalPrice: 467.22,
    quantity: 28,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.4,
      count: 310,
    },
  },
  {
    id: 18,
    title: "Nokia G60 5G",
    price: 349.0,
    description: "6.58-inch FHD+, Snapdragon 695, 6GB RAM, 128GB storage.",
    category: "Smartphones",
    image: "https://m.media-amazon.com/images/I/71g+3VPUSHL._AC_SL1500_.jpg",
    offer: "19% OFF",
    offerPrice: 282.69,
    finalPrice: 282.69,
    quantity: 0,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.0,
      count: 140,
    },
  },
  {
    id: 19,
    title: "Sony WH-1000XM5",
    price: 399.99,
    description:
      "Industry-leading noise canceling, 30-hour battery life, premium sound.",
    category: "Headphones",
    image: "https://m.media-amazon.com/images/I/71hXKWI1yTL._AC_SL1500_.jpg",
    offer: "15% OFF",
    offerPrice: 339.99,
    finalPrice: 339.99,
    quantity: 25,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.9,
      count: 1200,
    },
  },
  {
    id: 20,
    title: "Bose QuietComfort 45",
    price: 329.0,
    description:
      "Acoustic noise canceling, lightweight design, 24-hour battery.",
    category: "Headphones",
    image: "https://m.media-amazon.com/images/I/51aw022aEaL._AC_SL1500_.jpg",
    offer: "10% OFF",
    offerPrice: 296.1,
    finalPrice: 296.1,
    quantity: 18,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.8,
      count: 980,
    },
  },
  {
    id: 21,
    title: "Apple AirPods Max",
    price: 549.0,
    description:
      "High-fidelity audio, active noise cancellation, spatial audio.",
    category: "Headphones",
    image: "https://m.media-amazon.com/images/I/51t0IE0zjaL._AC_SL1500_.jpg",
    offer: "0",
    bestseller: true,
    offerPrice: 0,
    finalPrice: 549.0,
    quantity: 14,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.7,
      count: 850,
    },
  },
  {
    id: 22,
    title: "Sennheiser Momentum 4",
    price: 349.95,
    description:
      "Superior sound, 60-hour battery life, adaptive noise cancellation.",
    category: "Headphones",
    image: "https://m.media-amazon.com/images/I/716++4xC2wL._AC_SL1500_.jpg",
    offer: "17% OFF",
    offerPrice: 290.46,
    finalPrice: 290.46,
    quantity: 20,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.6,
      count: 610,
    },
  },
  {
    id: 23,
    title: "Beats Studio3 Wireless",
    price: 349.95,
    description:
      "Active noise canceling, Apple W1 chip, up to 22 hours battery.",
    category: "Headphones",
    image: "https://m.media-amazon.com/images/I/41oMRMiGMcL._AC_SL1038_.jpg",
    offer: "20% OFF",
    offerPrice: 279.96,
    finalPrice: 279.96,
    quantity: 22,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.5,
      count: 770,
    },
  },
  {
    id: 24,
    title: "Jabra Elite 85h",
    price: 249.99,
    description: "SmartSound audio, 36-hour battery, rain-resistant.",
    category: "Headphones",
    image: "https://m.media-amazon.com/images/I/81C6mZcbyuL._AC_SL1500_.jpg",
    offer: "18% OFF",
    offerPrice: 204.99,
    finalPrice: 204.99,
    quantity: 15,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.4,
      count: 540,
    },
  },
  {
    id: 25,
    title: "Anker Soundcore Life Q35",
    price: 129.99,
    description: "Hi-Res Audio, multi-mode noise canceling, 40-hour playtime.",
    category: "Headphones",
    image: "https://m.media-amazon.com/images/I/61UjWbuT5HL._AC_SL1500_.jpg",
    offer: "22% OFF",
    offerPrice: 101.39,
    finalPrice: 101.39,
    quantity: 28,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.3,
      count: 460,
    },
  },
  {
    id: 26,
    title: "AKG N700NC M2",
    price: 199.99,
    description:
      "Signature AKG sound, adaptive noise cancellation, foldable design.",
    category: "Headphones",
    image: "https://m.media-amazon.com/images/I/611DSbBH6GL._AC_SL1500_.jpg",
    offer: "25% OFF",
    offerPrice: 149.99,
    finalPrice: 149.99,
    quantity: 19,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.2,
      count: 320,
    },
  },
  {
    id: 27,
    title: "Logitech G Pro X Wireless",
    price: 229.99,
    description: "DTS Headphone:X 2.0, Blue VO!CE mic tech, lossless audio.",
    category: "Headphones",
    image: "https://m.media-amazon.com/images/I/51Vqs9NufmL._AC_SL1000_.jpg",
    offer: "15% OFF",
    offerPrice: 195.49,
    finalPrice: 195.49,
    quantity: 30,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.6,
      count: 510,
    },
  },
  {
    id: 28,
    title: "SteelSeries Arctis Nova Pro",
    price: 349.99,
    description: "360° spatial audio, active noise canceling, dual USB system.",
    category: "Headphones",
    image: "https://m.media-amazon.com/images/I/614IQytqAuL._AC_SL1500_.jpg",
    offer: "19% OFF",
    offerPrice: 283.49,
    finalPrice: 283.49,
    quantity: 16,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.7,
      count: 440,
    },
  },
  {
    id: 29,
    title: "Canon EOS R6 Mirrorless Camera",
    price: 2499.0,
    description:
      "20MP full-frame CMOS sensor, 4K video, 20 fps continuous shooting.",
    category: "Cameras",
    image: "https://m.media-amazon.com/images/I/71xMB0--4yL._AC_SL1500_.jpg",
    offer: "10% OFF",
    offerPrice: 2249.1,
    finalPrice: 2249.1,
    quantity: 10,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.9,
      count: 350,
    },
  },
  {
    id: 30,
    title: "Sony Alpha a7 III",
    price: 1999.99,
    description:
      "24.2MP full-frame sensor, 4K HDR video, 5-axis stabilization.",
    category: "Cameras",
    image: "https://m.media-amazon.com/images/I/517CEyCXIHL._AC_SL1000_.jpg",
    offer: "12% OFF",
    offerPrice: 1759.99,
    finalPrice: 1759.99,
    quantity: 12,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.8,
      count: 420,
    },
  },
  {
    id: 31,
    title: "Nikon Z6 II FX-Format",
    price: 1996.95,
    description:
      "24.5MP sensor, 4K UHD video, dual card slots, fast autofocus.",
    category: "Cameras",
    image: "https://m.media-amazon.com/images/I/81lKToo89wL._AC_SL1500_.jpg",
    offer: "15% OFF",
    offerPrice: 1697.41,
    finalPrice: 1697.41,
    quantity: 8,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.7,
      count: 300,
    },
  },
  {
    id: 32,
    title: "Fujifilm X-T4",
    price: 1699.0,
    description: "26.1MP APS-C sensor, in-body stabilization, 4K video.",
    category: "Cameras",
    image: "https://m.media-amazon.com/images/I/71BsdiTzEoL._AC_SL1500_.jpg",
    offer: "13% OFF",
    offerPrice: 1478.13,
    finalPrice: 1478.13,
    quantity: 15,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.6,
      count: 280,
    },
  },
  {
    id: 33,
    title: "Panasonic Lumix GH6",
    price: 2199.99,
    description:
      "Mirrorless Micro Four Thirds, 5.7K video, professional audio support.",
    category: "Cameras",
    image: "https://m.media-amazon.com/images/I/71ANGtyZRzL._AC_SL1500_.jpg",
    offer: "20% OFF",
    offerPrice: 1759.99,
    finalPrice: 1759.99,
    quantity: 9,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.5,
      count: 200,
    },
  },
  {
    id: 34,
    title: "GoPro HERO12 Black",
    price: 399.99,
    description: "5.3K video, HyperSmooth stabilization, waterproof design.",
    category: "Cameras",
    image: "https://m.media-amazon.com/images/I/81IzkXEug4L._AC_SL1500_.jpg",
    offer: "15% OFF",
    offerPrice: 339.99,
    finalPrice: 339.99,
    quantity: 25,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.6,
      count: 780,
    },
  },
  {
    id: 35,
    title: "DJI Pocket 3",
    price: 519.0,
    description:
      "Pocket-sized 4K gimbal camera, AI face tracking, 2-inch screen.",
    category: "Cameras",
    image: "https://m.media-amazon.com/images/I/514LEUejXYL._AC_SL1500_.jpg",
    offer: "18% OFF",
    offerPrice: 425.58,
    finalPrice: 425.58,
    quantity: 20,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.4,
      count: 160,
    },
  },
  {
    id: 36,
    title: "Samsung 65-inch QLED 4K Smart TV",
    price: 1299.99,
    description: "Quantum Dot technology, 4K UHD, Alexa built-in.",
    category: "TV",
    image: "https://m.media-amazon.com/images/I/71T3tmMx2FL._AC_SL1224_.jpg",
    offer: "14% OFF",
    offerPrice: 1117.99,
    finalPrice: 1117.99,
    quantity: 18,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.8,
      count: 940,
    },
  },
  {
    id: 37,
    title: "LG 55-inch OLED evo C3",
    price: 1799.99,
    description: "OLED evo display, Dolby Vision, webOS Smart TV.",
    category: "TV",
    image: "https://m.media-amazon.com/images/I/51Zqmgc9nRL._AC_SL1001_.jpg",
    offer: "17% OFF",
    offerPrice: 1493.99,
    finalPrice: 1493.99,
    quantity: 10,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.9,
      count: 820,
    },
  },
  {
    id: 38,
    title: "Sony Bravia XR 65-inch OLED",
    price: 2199.99,
    description: "Cognitive Processor XR, 4K UHD, Google TV.",
    category: "TV",
    image: "https://m.media-amazon.com/images/I/71ZAqOVL0bL._AC_SL1500_.jpg",
    offer: "16% OFF",
    offerPrice: 1847.99,
    finalPrice: 1847.99,
    quantity: 12,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.9,
      count: 670,
    },
  },
  {
    id: 39,
    title: "TCL 75-inch 6-Series 4K Mini-LED",
    price: 1199.99,
    description: "QLED with Mini-LED tech, Dolby Vision, Roku TV.",
    category: "TV",
    image: "https://m.media-amazon.com/images/I/41S1J6L9LRL._AC_SL1001_.jpg",
    offer: "20% OFF",
    offerPrice: 959.99,
    finalPrice: 959.99,
    quantity: 13,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.7,
      count: 510,
    },
  },
  {
    id: 40,
    title: "Hisense 55U8H 4K ULED TV",
    price: 799.99,
    description: "Quantum Dot Color, Dolby Atmos, Google TV.",
    category: "TV",
    image: "https://m.media-amazon.com/images/I/81g2EXBJfRL._AC_SL1500_.jpg",
    offer: "15% OFF",
    offerPrice: 679.99,
    finalPrice: 679.99,
    quantity: 17,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.5,
      count: 370,
    },
  },
  {
    id: 41,
    title: "Vizio 65-inch M6 Series",
    price: 699.99,
    description: "4K QLED, SmartCast platform, voice remote.",
    category: "TV",
    image: "https://m.media-amazon.com/images/I/81g4O3UXgiL._AC_SL1500_.jpg",
    offer: "12% OFF",
    offerPrice: 615.99,
    finalPrice: 615.99,
    quantity: 14,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.4,
      count: 310,
    },
  },
  {
    id: 42,
    title: "Samsung The Frame 50-inch QLED",
    price: 999.99,
    description: "Art Mode display, 4K QLED, customizable bezels.",
    category: "TV",
    image: "https://m.media-amazon.com/images/I/61muqHtz11L._AC_SL1002_.jpg",
    offer: "18% OFF",
    offerPrice: 819.99,
    finalPrice: 819.99,
    quantity: 11,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.6,
      count: 280,
    },
  },
  {
    id: 43,
    title: "Sharp 50-inch 4K UHD Android TV",
    price: 479.99,
    description: "4K HDR, built-in Chromecast, voice control remote.",
    category: "TV",
    image: "https://m.media-amazon.com/images/I/81V8cp87XGL._AC_SL1500_.jpg",
    offer: "20% OFF",
    offerPrice: 383.99,
    finalPrice: 383.99,
    quantity: 22,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.2,
      count: 210,
    },
  },
  {
    id: 44,
    title: "Philips 58-inch 4K UHD LED Smart TV",
    price: 599.99,
    description: "HDR10+, DTS HD, Android TV, voice search.",
    category: "TV",
    image: "https://m.media-amazon.com/images/I/71dXXB++bvL._AC_SL1500_.jpg",
    offer: "22% OFF",
    offerPrice: 467.99,
    finalPrice: 467.99,
    quantity: 20,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.3,
      count: 190,
    },
  },
  {
    id: 45,
    title: "MacBook Air 13-inch M2 Chip (2022)",
    price: 1199.0,
    description:
      "Apple M2 chip with 8-core CPU, 8GB RAM, 256GB SSD, Liquid Retina display.",
    category: "Laptops&Computers",
    image: "https://m.media-amazon.com/images/I/51u6rEpExeL._AC_SL1500_.jpg",
    offer: "10% OFF",
    offerPrice: 1079.1,
    finalPrice: 1079.1,
    quantity: 15,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.9,
      count: 920,
    },
  },
  {
    id: 46,
    title: "MacBook Pro 14-inch M2 Pro (2023)",
    price: 1999.0,
    description:
      "M2 Pro chip, 16GB unified memory, 512GB SSD, Liquid Retina XDR display.",
    category: "Laptops&Computers",
    image: "https://m.media-amazon.com/images/I/71jMWmZZ0ML._AC_SL1500_.jpg",
    offer: "12% OFF",
    offerPrice: 1759.12,
    finalPrice: 1759.12,
    quantity: 10,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.8,
      count: 670,
    },
  },
  {
    id: 47,
    title: "MacBook Pro 16-inch M2 Max (2023)",
    price: 3499.0,
    description:
      "M2 Max chip, 32GB RAM, 1TB SSD, best-in-class performance for pro users.",
    category: "Laptops&Computers",
    image: "https://m.media-amazon.com/images/I/515NVAtLK2L._AC_SL1145_.jpg",
    offer: "15% OFF",
    offerPrice: 2974.15,
    finalPrice: 2974.15,
    quantity: 5,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.9,
      count: 350,
    },
  },
  {
    id: 48,
    title: "MacBook Air 15-inch M2 Chip (2023)",
    price: 1299.0,
    description:
      "M2 chip, 8GB RAM, 256GB SSD, ultra-slim design with great battery life.",
    category: "Laptops&Computers",
    image: "https://m.media-amazon.com/images/I/61DeZsoTCjL._AC_SL1500_.jpg",
    offer: "8% OFF",
    offerPrice: 1195.08,
    finalPrice: 1195.08,
    quantity: 8,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.7,
      count: 430,
    },
  },
  {
    id: 49,
    title: "MacBook Pro 13-inch M2 (2022)",
    price: 1299.0,
    description:
      "M2 chip, 8GB RAM, 256GB SSD, Touch Bar, active cooling system.",
    category: "Laptops&Computers",
    image: "https://m.media-amazon.com/images/I/41Ajp4d8WwL._AC_SL1380_.jpg",
    offer: "10% OFF",
    offerPrice: 1169.1,
    finalPrice: 1169.1,
    quantity: 12,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.6,
      count: 550,
    },
  },
  {
    id: 50,
    title: "MacBook Air M1 (2020)",
    price: 999.0,
    description:
      "Apple M1 chip, 8GB RAM, 256GB SSD, fanless design, super quiet.",
    category: "Laptops&Computers",
    image: "https://m.media-amazon.com/images/I/71vFKBpKakL._AC_SL1500_.jpg",
    offer: "20% OFF",
    offerPrice: 799.2,
    finalPrice: 799.2,
    quantity: 20,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.9,
      count: 1300,
    },
  },
  {
    id: 51,
    title: "MacBook Pro 16-inch Intel i9 (2019)",
    price: 2399.0,
    description: "Intel Core i9, AMD Radeon Pro 5500M, 16GB RAM, 1TB SSD.",
    category: "Laptops&Computers",
    image: "https://m.media-amazon.com/images/I/514xtHOcqbL._AC_SL1500_.jpg",
    offer: "25% OFF",
    offerPrice: 1799.25,
    finalPrice: 1799.25,
    quantity: 6,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.5,
      count: 260,
    },
  },
  {
    id: 52,
    title: "Refurbished MacBook Pro 15-inch 2018",
    price: 1499.0,
    description: "Intel Core i7, 16GB RAM, 512GB SSD, Radeon Pro graphics.",
    category: "Laptops&Computers",
    image: "https://m.media-amazon.com/images/I/61oHdvv4vsL._AC_SL1500_.jpg",
    offer: "30% OFF",
    offerPrice: 1049.3,
    finalPrice: 1049.3,
    quantity: 7,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.3,
      count: 180,
    },
  },
  {
    id: 53,
    title: "MacBook Air M3 (Rumored Concept)",
    price: 1399.0,
    description:
      "Expected M3 chip, ultra-thin, more efficient and powerful design.",
    category: "Laptops&Computers",
    image: "https://m.media-amazon.com/images/I/51nQJi7RvAL._AC_SL1500_.jpg",
    offer: "Preorder - Save 5%",
    offerPrice: 1329.05,
    finalPrice: 1329.05,
    quantity: 4,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.0,
      count: 75,
    },
  },
  {
    id: 54,
    title: "Logitech G502 HERO Wired Gaming Mouse",
    price: 49.99,
    description:
      "High-performance wired gaming mouse with HERO 25K sensor and customizable buttons.",
    category: "Gaming Accessories",
    image: "https://m.media-amazon.com/images/I/61mpMH5TzkL._AC_SL1500_.jpg",
    offer: "15% OFF",
    offerPrice: 42.49,
    finalPrice: 42.49,
    quantity: 30,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.8,
      count: 2200,
    },
  },
  {
    id: 55,
    title: "Razer BlackWidow V3 Mechanical Gaming Keyboard",
    price: 139.99,
    description:
      "Green mechanical switches, RGB lighting, ergonomic wrist rest for pro gamers.",
    category: "Gaming Accessories",
    image: "https://m.media-amazon.com/images/I/71MMyY42UHL._AC_SL1500_.jpg",
    offer: "20% OFF",
    offerPrice: 111.99,
    finalPrice: 111.99,
    quantity: 18,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.7,
      count: 1500,
    },
  },
  {
    id: 56,
    title: "Corsair HS80 RGB Wireless Gaming Headset",
    price: 149.99,
    description:
      "Immersive sound with Dolby Atmos, wireless, RGB lighting, and ultra comfort.",
    category: "Gaming Accessories",
    image: "https://m.media-amazon.com/images/I/61LSZY5nk4L._AC_SL1000_.jpg",
    offer: "10% OFF",
    offerPrice: 134.99,
    finalPrice: 134.99,
    quantity: 10,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.6,
      count: 860,
    },
  },
  {
    id: 57,
    title: "SteelSeries QcK Gaming Mouse Pad - XXL",
    price: 39.99,
    description:
      "Cloth surface optimized for gaming sensors with non-slip rubber base.",
    category: "Gaming Accessories",
    image: "https://m.media-amazon.com/images/I/41ehSSG5VlL._AC_SL1500_.jpg",
    offer: "25% OFF",
    offerPrice: 29.99,
    finalPrice: 29.99,
    quantity: 40,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.9,
      count: 4100,
    },
  },
  {
    id: 58,
    title: "Elgato Stream Deck Mini",
    price: 79.99,
    description:
      "Compact live production controller with 6 customizable LCD keys.",
    category: "Gaming Accessories",
    image: "https://m.media-amazon.com/images/I/71aY+mfIxiL._AC_SL1500_.jpg",
    offer: "15% OFF",
    offerPrice: 67.99,
    finalPrice: 67.99,
    quantity: 6,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.8,
      count: 940,
    },
  },
  {
    id: 59,
    title: "Xbox Wireless Controller - Carbon Black",
    price: 59.99,
    description:
      "Textured grip, hybrid D-pad, and wireless support for Xbox and PC.",
    category: "Gaming Accessories",
    image: "https://m.media-amazon.com/images/I/512LVHxvkjL._SL1500_.jpg",
    offer: "10% OFF",
    offerPrice: 53.99,
    finalPrice: 53.99,
    quantity: 20,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.9,
      count: 3600,
    },
  },
  {
    id: 60,
    title: "PlayStation DualSense Wireless Controller - White",
    price: 69.99,
    description:
      "Next-gen wireless controller with haptic feedback and adaptive triggers.",
    category: "Gaming Accessories",
    image: "https://m.media-amazon.com/images/I/519ayRwl1AL._SL1500_.jpg",
    offer: "12% OFF",
    offerPrice: 61.59,
    finalPrice: 61.59,
    quantity: 25,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.8,
      count: 4300,
    },
  },
  {
    id: 61,
    title: "Razer Kiyo Streaming Webcam with Ring Light",
    price: 99.99,
    description:
      "1080p 30FPS video quality and built-in adjustable ring light for streamers.",
    category: "Gaming Accessories",
    image: "https://m.media-amazon.com/images/I/71zTLsSWngL._AC_SL1500_.jpg",
    offer: "20% OFF",
    offerPrice: 79.99,
    finalPrice: 79.99,
    quantity: 8,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.5,
      count: 670,
    },
  },
  {
    id: 62,
    title: "Logitech G920 Driving Force Racing Wheel",
    price: 299.99,
    description:
      "Force feedback racing wheel for Xbox and PC with responsive pedals.",
    category: "Gaming Accessories",
    image: "https://m.media-amazon.com/images/I/71-ZeHPle7L._SL1500_.jpg",
    offer: "15% OFF",
    offerPrice: 254.99,
    finalPrice: 254.99,
    quantity: 4,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.7,
      count: 1200,
    },
  },
  {
    id: 63,
    title: "HyperX Cloud II Gaming Headset",
    price: 89.99,
    description:
      "Premium sound, memory foam ear pads, detachable mic, great for long sessions.",
    category: "Gaming Accessories",
    image: "https://m.media-amazon.com/images/I/71R47a0011L._AC_SL1500_.jpg",
    offer: "18% OFF",
    offerPrice: 73.79,
    finalPrice: 73.79,
    quantity: 12,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.6,
      count: 2400,
    },
  },
  {
    id: 64,
    title: "ASUS ROG Gaming Mouse Pad - RGB",
    price: 59.99,
    description:
      "Extra-large mouse pad with RGB lighting and smooth surface for precision.",
    category: "Gaming Accessories",
    image: "https://m.media-amazon.com/images/I/61M2CGr3NPL._AC_SL1500_.jpg",
    offer: "10% OFF",
    offerPrice: 53.99,
    finalPrice: 53.99,
    quantity: 15,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.4,
      count: 510,
    },
  },
  {
    id: 65,
    title: "AverMedia Live Gamer Portable 2 Plus",
    price: 149.99,
    description:
      "Capture 1080p60 video from consoles and PC with zero-lag pass-through.",
    category: "Gaming Accessories",
    image: "https://m.media-amazon.com/images/I/51mydAq7wQL._AC_SL1000_.jpg",
    offer: "12% OFF",
    offerPrice: 131.99,
    finalPrice: 131.99,
    quantity: 9,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.3,
      count: 460,
    },
  },
  {
    id: 66,
    title: "MSI Gaming Monitor 27-inch Curved 165Hz",
    price: 299.99,
    description:
      "Curved gaming monitor with 165Hz refresh rate and 1ms response time.",
    category: "Gaming Accessories",
    image: "https://m.media-amazon.com/images/I/71Rcg0lXJrL._AC_SL1500_.jpg",
    offer: "15% OFF",
    offerPrice: 254.99,
    finalPrice: 254.99,
    quantity: 6,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.7,
      count: 980,
    },
  },
  {
    id: 67,
    title: "Redragon K552 Mechanical Gaming Keyboard",
    price: 49.99,
    description:
      "Compact mechanical keyboard with red switches and rainbow lighting.",
    category: "Gaming Accessories",
    image: "https://m.media-amazon.com/images/I/71FSIp+tDNL._AC_SL1500_.jpg",
    offer: "25% OFF",
    offerPrice: 37.49,
    finalPrice: 37.49,
    quantity: 22,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.6,
      count: 1350,
    },
  },
  {
    id: 68,
    title: "Turtle Beach Recon 200 Gen 2 Headset",
    price: 59.99,
    description:
      "Amplified wired headset with bass boost and flip-to-mute mic.",
    category: "Gaming Accessories",
    image: "https://m.media-amazon.com/images/I/41+tdZn1MgL.jpg",
    offer: "10% OFF",
    offerPrice: 53.99,
    finalPrice: 53.99,
    quantity: 13,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.3,
      count: 770,
    },
  },
  {
    id: 69,
    title: "Cooler Master RGB Gaming Chair",
    price: 299.0,
    description:
      "Ergonomic gaming chair with adjustable armrests and RGB lighting.",
    category: "Gaming Accessories",
    image: "https://m.media-amazon.com/images/I/81bsYDdcfsL._AC_SL1500_.jpg",
    offer: "20% OFF",
    offerPrice: 239.2,
    finalPrice: 239.2,
    quantity: 3,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.5,
      count: 390,
    },
  },
  {
    id: 70,
    title: "Samsung 980 PRO 1TB PCIe Gen4 NVMe SSD",
    price: 129.99,
    description:
      "High-speed NVMe SSD with read speeds up to 7000MB/s, ideal for gaming and performance PCs.",
    category: "SSD Hards and Graphic Cards",
    image: "https://m.media-amazon.com/images/I/713h+shZfQL._AC_SL1500_.jpg",
    offer: "0",
    offerPrice: 0,
    finalPrice: 129.99,
    quantity: 20,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.9,
      count: 2700,
    },
  },
  {
    id: 71,
    title: "WD Black SN850X 2TB NVMe SSD",
    price: 219.99,
    description:
      "Ultra-fast gaming SSD with PCIe Gen4 technology and Heatsink.",
    category: "SSD Hards and Graphic Cards",
    image: "https://m.media-amazon.com/images/I/71n60wEn32L._AC_SL1500_.jpg",
    offer: "0",
    offerPrice: 0,
    finalPrice: 219.99,
    quantity: 12,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.8,
      count: 1600,
    },
  },
  {
    id: 72,
    title: "Crucial MX500 500GB 2.5-Inch SATA SSD",
    price: 59.99,
    description:
      "Reliable SATA SSD with integrated power loss immunity and AES encryption.",
    category: "SSD Hards and Graphic Cards",
    image: "https://m.media-amazon.com/images/I/81OXQ57jsSS._AC_SL1500_.jpg",
    offer: "0",
    offerPrice: 0,
    finalPrice: 59.99,
    quantity: 30,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.7,
      count: 3100,
    },
  },
  {
    id: 73,
    title: "Seagate FireCuda 530 1TB Heatsink SSD",
    price: 149.99,
    description: "High-endurance Gen4 SSD designed for PS5 and gaming PCs.",
    category: "SSD Hards and Graphic Cards",
    image: "https://m.media-amazon.com/images/I/41AKEuDi07L.jpg",
    offer: "0",
    offerPrice: 0,
    finalPrice: 149.99,
    quantity: 8,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.6,
      count: 850,
    },
  },
  {
    id: 74,
    title: "Kingston A400 240GB SSD",
    price: 32.99,
    description:
      "Affordable SSD upgrade with fast boot times and quick load speeds.",
    category: "SSD Hards and Graphic Cards",
    image: "https://m.media-amazon.com/images/I/51zhuXxYuRL._AC_SL1080_.jpg",
    offer: "0",
    offerPrice: 0,
    finalPrice: 32.99,
    quantity: 45,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.5,
      count: 5000,
    },
  },
  {
    id: 75,
    title: "Gigabyte GeForce RTX 4070 Ti 12GB",
    price: 799.99,
    description:
      "Powerful GPU with ray tracing and DLSS 3 support, ideal for 4K gaming.",
    category: "SSD Hards and Graphic Cards",
    image: "https://m.media-amazon.com/images/I/71sQ0ncdF-L._AC_SL1500_.jpg",
    offer: "0",
    offerPrice: 0,
    finalPrice: 799.99,
    quantity: 6,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.9,
      count: 1200,
    },
  },
  {
    id: 76,
    title: "MSI Radeon RX 6800 XT Gaming X Trio 16GB",
    price: 699.99,
    description:
      "AMD graphics card optimized for performance, VR gaming, and high-res visuals.",
    category: "SSD Hards and Graphic Cards",
    image: "https://m.media-amazon.com/images/I/81L7-qPS0ZL._AC_SL1500_.jpg",
    offer: "0",
    offerPrice: 0,
    finalPrice: 699.99,
    quantity: 4,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.8,
      count: 900,
    },
  },
  {
    id: 77,
    title: "ASUS TUF Gaming GeForce RTX 3060 Ti",
    price: 449.99,
    description:
      "Reliable GPU with dual-ball fan bearings and auto-extreme manufacturing.",
    category: "SSD Hards and Graphic Cards",
    image: "https://m.media-amazon.com/images/I/61TBmZsQs0L._AC_SL1000_.jpg",
    offer: "0",
    offerPrice: 0,
    finalPrice: 449.99,
    quantity: 7,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.7,
      count: 1600,
    },
  },
  {
    id: 78,
    title: "Zotac Gaming GeForce GTX 1660 Super",
    price: 249.99,
    description: "Mid-range GPU for budget gaming builds with GDDR6 memory.",
    category: "SSD Hards and Graphic Cards",
    image: "https://m.media-amazon.com/images/I/71SJpDyS63L._AC_SL1500_.jpg",
    offer: "0",
    offerPrice: 0,
    finalPrice: 249.99,
    quantity: 11,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.5,
      count: 2100,
    },
  },
  {
    id: 79,
    title: "Sapphire Pulse AMD Radeon RX 6700 XT",
    price: 479.99,
    description: "1440p gaming performance with dual-X cooling technology.",
    category: "SSD Hards and Graphic Cards",
    image: "https://m.media-amazon.com/images/I/81cRh290cyL._SL1500_.jpg",
    offer: "0",
    offerPrice: 0,
    finalPrice: 479.99,
    quantity: 5,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.6,
      count: 880,
    },
  },
  {
    id: 80,
    title: "Intel 670p Series 1TB M.2 NVMe SSD",
    price: 109.99,
    description:
      "Affordable PCIe 3.0 SSD with high performance for laptops and desktops.",
    category: "SSD Hards and Graphic Cards",
    image: "https://m.media-amazon.com/images/I/61ezTUPtLxL._AC_SL1500_.jpg",
    offer: "0",
    offerPrice: 0,
    finalPrice: 109.99,
    quantity: 14,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.3,
      count: 600,
    },
  },
  {
    id: 81,
    title: "PNY CS900 1TB SATA SSD",
    price: 69.99,
    description:
      "Reliable upgrade solution for faster OS boot and application loading.",
    category: "SSD Hards and Graphic Cards",
    image: "https://m.media-amazon.com/images/I/61cyHqB+KmL._AC_SL1000_.jpg",
    offer: "0",
    offerPrice: 0,
    finalPrice: 69.99,
    quantity: 28,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.6,
      count: 2200,
    },
  },
  {
    id: 82,
    title: "TeamGroup T-Force Cardea Z440 1TB Gen4 SSD",
    price: 124.99,
    description:
      "PCIe Gen4 SSD with graphene heatsink for high-end performance.",
    category: "SSD Hards and Graphic Cards",
    image: "https://m.media-amazon.com/images/I/71eEUOvrHoL._AC_SL1200_.jpg",
    offer: "0",
    offerPrice: 0,
    finalPrice: 124.99,
    quantity: 10,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.4,
      count: 490,
    },
  },
  {
    id: 83,
    title: "GALAX GeForce RTX 3060 12GB",
    price: 389.99,
    description: "Efficient and budget-friendly RTX gaming GPU with dual fans.",
    category: "SSD Hards and Graphic Cards",
    image: "https://m.media-amazon.com/images/I/51xp3V8t49L._AC_SL1000_.jpg",
    offer: "0",
    offerPrice: 0,
    finalPrice: 389.99,
    quantity: 8,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.5,
      count: 700,
    },
  },
  {
    id: 84,
    title: "ASRock Phantom Gaming D Radeon RX 570",
    price: 179.99,
    description:
      "Older but reliable GPU for entry-level 1080p gaming and esports.",
    category: "SSD Hards and Graphic Cards",
    image: "https://m.media-amazon.com/images/I/51VG+Qk9QdL._AC_SL1000_.jpg",
    offer: "0",
    offerPrice: 0,
    finalPrice: 179.99,
    quantity: 9,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.2,
      count: 1300,
    },
  },
  {
    id: 85,
    title: "ADATA XPG GAMMIX S70 Blade 2TB Gen4 SSD",
    price: 199.99,
    description:
      "Top-tier SSD with ultra-fast Gen4 speed and heatsink for PS5/PC.",
    category: "SSD Hards and Graphic Cards",
    image: "https://m.media-amazon.com/images/I/51nYrnv09aL._AC_SL1500_.jpg",
    offer: "0",
    offerPrice: 0,
    finalPrice: 199.99,
    quantity: 7,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.7,
      count: 730,
    },
  },
  {
    id: 86,
    title: "Anker 733 Power Bank (GaNPrime PowerCore 65W)",
    price: 99.99,
    description:
      "A versatile 2-in-1 device that functions as both a high-speed wall charger and a portable power bank with a 10,000mAh capacity.",
    category: "Power Banks",
    image: "https://m.media-amazon.com/images/I/71BQb61GmNL._AC_SL1500_.jpg",
    offer: "0",
    offerPrice: 0,
    finalPrice: 99.99,
    quantity: 15,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.8,
      count: 1200,
    },
  },
  {
    id: 87,
    title: "UGREEN Nexode Power Bank 20000mAh 130W",
    price: 129.99,
    description:
      "High-capacity power bank with 130W PD fast charging, featuring a smart TFT display and three USB-C ports for simultaneous charging.",
    category: "Power Banks",
    image: "https://m.media-amazon.com/images/I/71tN4caOWRL._AC_SL1500_.jpg",
    offer: "0",
    offerPrice: 0,
    finalPrice: 129.99,
    quantity: 10,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.7,
      count: 950,
    },
  },
  {
    id: 88,
    title: "Anker 737 Power Bank 24000mAh 140W",
    price: 149.99,
    description:
      "High-performance portable charger with 140W output and three ports, suitable for charging laptops, tablets, and smartphones.",
    category: "Power Banks",
    image: "https://m.media-amazon.com/images/I/71kttSQ2r4L._AC_SL1500_.jpg",
    offer: "0",
    offerPrice: 0,
    finalPrice: 149.99,
    quantity: 8,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.9,
      count: 1100,
    },
  },
  {
    id: 89,
    title: "INIU 64 140W Power Bank",
    price: 119.99,
    description:
      "Portable charger with a 27,000mAh capacity and 140W output, featuring a smart digital display and USB-C In-N-Out functionality.",
    category: "Power Banks",
    image: "https://m.media-amazon.com/images/I/61btVyNT2dL._AC_SL1500_.jpg",
    offer: "0",
    offerPrice: 0,
    finalPrice: 119.99,
    quantity: 12,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.6,
      count: 800,
    },
  },
  {
    id: 90,
    title: "GT19 Ultra Power Bank",
    price: 139.99,
    description:
      "Features 140W USB-C fast charging with a full recharge in 19 minutes, 175W total output across three ports, and a smart TFT display.",
    category: "Power Banks",
    image: "https://m.media-amazon.com/images/I/61+wDBLEQ8L._AC_SL1500_.jpg",
    offer: "0",
    offerPrice: 0,
    finalPrice: 139.99,
    quantity: 9,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.7,
      count: 700,
    },
  },
  {
    id: 91,
    title: "Energy QC 120W Power Bank",
    price: 109.99,
    description:
      "Offers a 27,000mAh capacity with 120W output, three ports, and a 99.9Wh rating, making it travel-friendly.",
    category: "Power Banks",
    image: "https://m.media-amazon.com/images/I/41-j9YaY8WL._AC_.jpg",
    offer: "0",
    offerPrice: 0,
    finalPrice: 109.99,
    quantity: 14,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.5,
      count: 650,
    },
  },
  {
    id: 92,
    title: "Anker PowerCore Prime 27600mAh Power Bank",
    price: 159.99,
    description:
      "High-performance portable charger with a 27,600mAh capacity and advanced 250W total output, featuring multiple ports and a smart digital display.",
    category: "Power Banks",
    image: "https://m.media-amazon.com/images/I/61JGUEIcAQL._AC_SL1500_.jpg",
    offer: "0",
    offerPrice: 0,
    finalPrice: 159.99,
    quantity: 7,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.8,
      count: 900,
    },
  },
  {
    id: 93,
    title: "Anker Nano Power Bank",
    price: 49.99,
    description:
      "Compact and highly efficient power bank with a built-in USB-C connector and fast charging speeds, featuring advanced PowerIQ technology.",
    category: "Power Banks",
    image: "https://m.media-amazon.com/images/I/51Yi2Q7zZlL._AC_SL1500_.jpg",
    offer: "0",
    offerPrice: 0,
    finalPrice: 49.99,
    quantity: 20,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.6,
      count: 1100,
    },
  },
  {
    id: 94,
    title: "Nupd 22.5W 20000mAh Power Bank",
    price: 59.99,
    description:
      "High-capacity portable charger with fast and reliable charging, featuring Power Delivery and Quick Charge technologies.",
    category: "Power Banks",
    image: "https://m.media-amazon.com/images/I/51aZGPrKBbL._AC_SL1215_.jpg",
    offer: "0",
    offerPrice: 0,
    finalPrice: 59.99,
    quantity: 18,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.5,
      count: 850,
    },
  },
  {
    id: 95,
    title: "Anker PowerCore GoHub Slim",
    price: 79.99,
    description:
      "Portable charger with a built-in wall plug, 10,000mAh capacity, integrated cables, and additional USB-C port for simultaneous charging.",
    category: "Power Banks",
    image: "https://m.media-amazon.com/images/I/71Sn62lz-PL._AC_SL1500_.jpg",
    offer: "0",
    offerPrice: 0,
    finalPrice: 79.99,
    quantity: 13,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.7,
      count: 750,
    },
  },
  {
    id: 96,
    title: "RAVPower 20000mAh Power Bank",
    price: 69.99,
    description:
      "High-capacity power bank with 20W PD fast charging, featuring multiple ports and a compact design.",
    category: "Power Banks",
    image: "https://m.media-amazon.com/images/I/71CqeXKdEeL._AC_SL1500_.jpg",
    offer: "0",
    offerPrice: 0,
    finalPrice: 69.99,
    quantity: 16,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.4,
      count: 600,
    },
  },
  {
    id: 97,
    title: "RAVPower 10000mAh Power Bank",
    price: 39.99,
    description:
      "Compact and lightweight power bank with 18W PD fast charging and multiple ports.",
    category: "Power Banks",
    image: "https://m.media-amazon.com/images/I/71TzGS7EiIL._AC_SL1500_.jpg",
    offer: "0",
    offerPrice: 0,
    finalPrice: 39.99,
    quantity: 25,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.5,
      count: 1200,
    },
  },
  {
    id: 98,
    title: "RAVPower 30000mAh Power Bank",
    price: 89.99,
    description:
      "High-capacity power bank with 30W PD fast charging and multiple ports.",
    category: "Power Banks",
    image: "https://m.media-amazon.com/images/I/61ouHCMOkpL._AC_SL1500_.jpg",
    offer: "0",
    offerPrice: 0,
    finalPrice: 89.99,
    quantity: 10,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.6,
      count: 800,
    },
  },
  {
    id: 99,
    title: "RAVPower 50000mAh Power Bank",
    price: 129.99,
    description:
      "Ultra-high-capacity power bank with 50W PD fast charging and multiple ports.",
    category: "Power Banks",
    image: "https://m.media-amazon.com/images/I/8167cg5sOuL._AC_SL1500_.jpg",
    offer: "0",
    offerPrice: 0,
    finalPrice: 129.99,
    quantity: 5,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.7,
      count: 600,
    },
  },
  {
    id: 100,
    title: "RAVPower 20000mAh Power Bank with AC Outlet",
    price: 99.99,
    description:
      "High-capacity power bank with AC outlet, 20W PD fast charging, and multiple ports.",
    category: "Power Banks",
    image: "https://m.media-amazon.com/images/I/51p3EuxuU7L._AC_SL1500_.jpg",
    offer: "0",
    offerPrice: 0,
    finalPrice: 99.99,
    quantity: 8,
    counter: 1,
    isMaxCount: false,
    rating: {
      rate: 4.8,
      count: 700,
    },
  },
];

export default productsList;
